"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Brain, Check, ChevronRight, CircleHelp, Clock3, Droplets, HeartPulse, RotateCcw, Sparkles, X } from "lucide-react";

type Level = "easy" | "hard";
const stationNames=["Vorwissen","Körperbild","Hinweg","Kapillaren","Rückweg","Blutweg","Zeichenwerkstatt","Abschluss"];
const easyRoute=["linke Herzkammer","Körperarterie","Körper","Körpervene","rechter Vorhof"];
const hardRoute=["linke Herzkammer","Aorta","Körperarterien","Arteriolen","Kapillaren","Venolen","Körpervenen","Hohlvenen","rechter Vorhof"];

export default function Home(){
  const [level,setLevel]=useState<Level|null>(null);const [station,setStation]=useState(0);const [idea,setIdea]=useState("");const [stage,setStage]=useState(0);const [organs,setOrgans]=useState<string[]>([]);const [exchange,setExchange]=useState<Record<number,string>>({});const [vessels,setVessels]=useState<Record<number,string>>({});const [sequence,setSequence]=useState<string[]>([]);const [flowResult,setFlowResult]=useState<"idle"|"ok"|"wrong">("idle");const [drawChecks,setDrawChecks]=useState<Record<number,boolean>>({});const [finalAnswers,setFinalAnswers]=useState<Record<number,string>>({});const [finalText,setFinalText]=useState("");
  const hard=level==="hard";const route=hard?hardRoute:easyRoute;const routeCorrect=useMemo(()=>sequence.join("|")===route.join("|"),[sequence,route]);
  function choose(l:Level){setLevel(l);setStation(0)}
  return <main className="min-h-screen bg-[var(--background)] text-[var(--foreground)]">
    <header className="sticky top-0 z-20 border-b border-sky-950/10 bg-white/92 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center gap-3 px-4 py-3 sm:px-8"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-rose-500 text-white"><HeartPulse/></div><div className="min-w-0 flex-1"><p className="text-xs font-black uppercase tracking-[.15em] text-sky-700">60-Minuten-Lernweg</p><h1 className="truncate text-lg font-black sm:text-xl">Der Körperkreislauf</h1></div>{level&&<button className="modebadge" onClick={()=>setLevel(null)}>{hard?"Knifflig":"Basis"} · wechseln</button>}</div>{level&&<div className="h-1 bg-sky-100"><div className="h-full bg-gradient-to-r from-rose-500 to-sky-500 transition-all" style={{width:`${(station+1)/8*100}%`}}/></div>}</header>
    {!level?<LevelChoice choose={choose}/>:<><div className="mx-auto max-w-6xl px-4 pt-5 sm:px-8"><div className="station-strip">{stationNames.map((n,i)=><button key={n} onClick={()=>setStation(i)} className={i===station?"current":i<station?"done":""}><span>{i<station?<Check size={14}/>:i+1}</span><b>{n}</b></button>)}</div></div>
      {station===0&&<StartScreen hard={hard} idea={idea} setIdea={setIdea}/>} 
      {station===1&&<BodyScreen hard={hard} stage={stage} setStage={setStage}/>} 
      {station===2&&<OutwardScreen hard={hard} organs={organs} setOrgans={setOrgans}/>} 
      {station===3&&<ExchangeScreen hard={hard} answers={exchange} setAnswers={setExchange}/>} 
      {station===4&&<ReturnScreen hard={hard} answers={vessels} setAnswers={setVessels}/>} 
      {station===5&&<RouteScreen hard={hard} route={route} sequence={sequence} setSequence={setSequence} result={flowResult} check={()=>setFlowResult(routeCorrect?"ok":"wrong")} reset={()=>{setSequence([]);setFlowResult("idle")}}/>} 
      {station===6&&<DrawingScreen hard={hard} checks={drawChecks} setChecks={setDrawChecks}/>} 
      {station===7&&<FinalScreen hard={hard} answers={finalAnswers} setAnswers={setFinalAnswers} text={finalText} setText={setFinalText}/>} 
      <nav className="mx-auto flex max-w-5xl items-center justify-between gap-3 px-4 pb-12 pt-2 sm:px-8"><button className="navbtn" disabled={station===0} onClick={()=>setStation(s=>Math.max(0,s-1))}><ArrowLeft size={18}/> Zurück</button><span className="text-center text-sm font-black text-slate-500">{stationNames[station]}<br/><span className="font-normal">Station {station+1} von 8</span></span><button className="navbtn" disabled={station===7} onClick={()=>setStation(s=>Math.min(7,s+1))}>Weiter <ArrowRight size={18}/></button></nav>
    </>}
  </main>
}

function LevelChoice({choose}:{choose:(l:Level)=>void}){return <section className="mx-auto max-w-5xl px-4 py-10 sm:px-8 sm:py-14"><span className="eyebrow">Nur der Körperkreislauf</span><h2 className="mt-3 max-w-4xl text-4xl font-black tracking-tight text-sky-950 sm:text-6xl">Verfolge den Weg des Blutes <span className="text-rose-500">durch deinen Körper.</span></h2><p className="mt-5 max-w-2xl text-lg leading-relaxed text-slate-600">Vom Start in der linken Herzkammer bis zur Ankunft im rechten Vorhof. Wähle deinen Lernweg.</p><div className="mt-8 grid gap-5 md:grid-cols-2"><button onClick={()=>choose("easy")} className="level-card border-sky-200 bg-sky-50 text-left"><span className="mb-5 grid h-14 w-14 place-items-center rounded-2xl bg-sky-500 text-white"><Droplets/></span><h3 className="text-2xl font-black text-sky-950">Basis · mit vielen Hilfen</h3><ul className="mt-3 space-y-2 text-slate-600"><li>✓ kurze Erklärungen</li><li>✓ fünf Stationen im Blutweg</li><li>✓ Zeichnen mit klaren Vorgaben</li><li>✓ sichtbare Merksätze</li></ul><Time text="etwa 55 Minuten"/><span className="mt-5 flex items-center gap-2 font-black text-sky-700">Basisweg starten <ChevronRight/></span></button><button onClick={()=>choose("hard")} className="level-card border-rose-200 bg-rose-50 text-left"><span className="mb-5 grid h-14 w-14 place-items-center rounded-2xl bg-rose-500 text-white"><Sparkles/></span><h3 className="text-2xl font-black text-sky-950">Knifflig · mit Fachsprache</h3><ul className="mt-3 space-y-2 text-slate-600"><li>✓ neun Stationen im Blutweg</li><li>✓ Arteriolen, Kapillaren und Venolen</li><li>✓ Stoffaustausch begründen</li><li>✓ ausführlicher Zeichenauftrag</li></ul><Time text="etwa 65 Minuten"/><span className="mt-5 flex items-center gap-2 font-black text-rose-700">Kniffligen Weg starten <ChevronRight/></span></button></div></section>}
function Time({text}:{text:string}){return <span className="mt-5 inline-flex items-center gap-2 rounded-full bg-white/80 px-3 py-2 text-sm font-black text-slate-600"><Clock3 size={17}/>{text}</span>}
function Shell({n,title,time,children}:{n:number,title:string,time:string,children:React.ReactNode}){return <section className="mx-auto max-w-5xl px-4 py-8 sm:px-8 sm:py-10"><div className="flex flex-wrap items-center gap-3"><span className="eyebrow">Station {n}</span><span className="timechip"><Clock3 size={15}/>{time}</span></div><h2 className="mb-7 mt-2 text-3xl font-black tracking-tight text-sky-950 sm:text-4xl">{title}</h2>{children}</section>}

function StartScreen({hard,idea,setIdea}:{hard:boolean,idea:string,setIdea:(v:string)=>void}){return <Shell n={1} title="Was weißt du schon über den Blutweg?" time={hard?"6 Minuten":"5 Minuten"}><div className="panel"><p className="text-xl font-black">Welche Aussage beschreibt einen Kreislauf?</p><div className="mt-5 grid gap-3">{["Das Blut fließt nur vom Herzen weg.","Das Blut fließt vom Herzen in den Körper und wieder zurück.","Das Blut bleibt in den Beinen stehen."].map(x=><Choice key={x} active={idea===x} onClick={()=>setIdea(x)} label={x}/>)}</div>{idea&&<Feedback ok={idea.includes("wieder zurück")} text={idea.includes("wieder zurück")?"Genau: Hinweg und Rückweg gehören zusammen.":"Ein Kreislauf braucht einen Hinweg und einen Rückweg. Versuche es noch einmal."}/>}</div>{hard&&<Task title="Vorwissen notieren">Welche Blutgefäße kennst du bereits? Notiere zusätzlich, worin sie sich deiner Meinung nach unterscheiden.</Task>}</Shell>}

function BodyScreen({hard,stage,setStage}:{hard:boolean,stage:number,setStage:(v:number)=>void}){const steps=hard?["Überblick","linke Herzkammer","Aorta und Arterien","Kapillaren","Venen und Hohlvenen","rechter Vorhof"]:["Überblick","Start","roter Hinweg","Austausch","blauer Rückweg","Ziel"];const texts=hard?["Orientiere dich: Der Körperkreislauf beginnt links im Herzen und endet rechts im Herzen.","Die linke Herzkammer erzeugt Druck und presst sauerstoffreiches Blut in die Aorta.","Aorta, Körperarterien und Arteriolen verzweigen sich bis in alle Körperteile.","In den Kapillaren gibt das Blut Sauerstoff und Nährstoffe ab und nimmt Kohlenstoffdioxid auf.","Venolen, Körpervenen und Hohlvenen sammeln das sauerstoffarme Blut und führen es zurück.","Im rechten Vorhof endet der Körperkreislauf."]:["Sieh dir zuerst Körper, Herz und Gefäße an.","Die linke Herzkammer ist der Start.","Körperarterien führen sauerstoffreiches Blut vom Herzen weg.","Im Körper gibt das Blut Sauerstoff ab.","Körpervenen bringen sauerstoffarmes Blut zurück.","Der rechte Vorhof ist das Ziel."];return <Shell n={2} title="Das Körperbild richtig lesen" time={hard?"8 Minuten":"7 Minuten"}><div className="color-key"><span><i className="key-red"/>Rot = sauerstoffreich</span><span><i className="key-blue"/>Blau = sauerstoffarm</span><strong>Echtes Blut ist nie blau.</strong></div><div className="circulation-lesson mt-5"><div className="panel diagram-panel"><BodyDiagram stage={stage}/></div><div className="panel step-panel"><h3 className="cardtitle">Baue die Abbildung auf</h3><div className="diagram-steps">{steps.map((s,i)=><button key={s} className={stage===i?"active":""} onClick={()=>setStage(i)}><span>{i}</span>{s}</button>)}</div><div className={`stage-explanation stage-${Math.min(stage,4)}`}><strong>Schritt {stage}</strong><p>{texts[stage]}</p></div></div></div><div className="direction-rule mt-5"><ArrowRight/><div><strong>Die Pfeile sind entscheidend.</strong><p>Sie zeigen, in welche Richtung das Blut fließt.</p></div></div></Shell>}

function BodyDiagram({stage}:{stage:number}){return <figure className="body-circuit-figure"><svg className="circuit-svg" viewBox="0 0 520 720" role="img" aria-labelledby="c-title c-desc"><title id="c-title">Körperkreislauf</title><desc id="c-desc">Roter Hinweg von der linken Herzkammer in den Körper und blauer Rückweg zum rechten Vorhof.</desc><defs><marker id="ar" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L0 6L7 3Z" fill="#d92d50"/></marker><marker id="ab" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L0 6L7 3Z" fill="#087cab"/></marker></defs><circle cx="260" cy="62" r="42" className="silhouette"/><path d="M205 121Q260 98 315 121L342 316Q330 355 309 371L326 660H275L260 410L245 660H194L211 371Q190 355 178 316Z" className="silhouette"/><path d="M190 145L82 346M330 145L438 346" className="limb"/><g className={stage>=1?"diagram-part visible":"diagram-part"}><path d="M239 204C214 179 194 215 212 245C225 267 260 288 260 288S295 267 308 245C326 215 306 179 281 204C270 215 260 224 260 224S250 215 239 204Z" fill="#f7b6c4" stroke="#8e2340" strokeWidth="4"/><path d="M260 224V280" stroke="#fff" strokeWidth="4"/><text x="155" y="198" className="svg-label red-label">linke Herzkammer</text><text x="292" y="198" className="svg-label blue-label">rechter Vorhof</text></g><g className={stage>=2?"diagram-part visible":"diagram-part"}><path d="M244 251C205 235 185 196 187 157C188 111 222 102 232 91M210 174L105 322M214 260C185 335 193 458 215 624M220 282C240 326 235 355 229 390M201 315L117 325" className="vessel red-vessel" markerEnd="url(#ar)"/><text x="55" y="135" className="svg-label red-label">Körperarterien</text></g><g className={stage>=3?"diagram-part visible":"diagram-part"}><circle cx="232" cy="91" r="10" className="capillary"/><circle cx="105" cy="322" r="10" className="capillary"/><circle cx="117" cy="325" r="10" className="capillary"/><circle cx="229" cy="390" r="10" className="capillary"/><circle cx="215" cy="624" r="10" className="capillary"/><circle cx="305" cy="624" r="10" className="capillary"/><text x="304" y="408" className="svg-label exchange-label">Kapillaren</text><text x="304" y="428" className="svg-small">Stoffaustausch</text></g><g className={stage>=4?"diagram-part visible":"diagram-part"}><path d="M288 91C306 98 327 105 330 130C337 171 329 210 288 226M415 322L309 173M305 624C327 458 335 335 306 260M291 390C285 355 280 326 300 282M403 325L319 315" className="vessel blue-vessel" markerEnd="url(#ab)"/><text x="325" y="135" className="svg-label blue-label">Körpervenen</text></g><g className={stage>=5?"diagram-part visible":"diagram-part"}><circle cx="288" cy="226" r="13" fill="#087cab"/><text x="260" y="695" textAnchor="middle" className="svg-caption">START: LINKE HERZKAMMER · ZIEL: RECHTER VORHOF</text></g></svg><figcaption>{stage<5?"Wähle den nächsten Schritt.":"Der vollständige Körperkreislauf."}</figcaption></figure>}

function OutwardScreen({hard,organs,setOrgans}:{hard:boolean,organs:string[],setOrgans:(v:string[])=>void}){const targets=["Kopf","Arme","innere Organe","Beine"];function toggle(x:string){setOrgans(organs.includes(x)?organs.filter(o=>o!==x):[...organs,x])}return <Shell n={3} title="Der rote Hinweg: vom Herzen in den Körper" time={hard?"8 Minuten":"7 Minuten"}><div className="grid gap-5 md:grid-cols-2"><div className="panel"><p className="label">Start</p><h3 className="cardtitle">Linke Herzkammer</h3><p className="mt-3 leading-relaxed">{hard?"Die kräftige Muskulatur der linken Herzkammer erzeugt hohen Druck. Das Blut gelangt zuerst in die Aorta und verteilt sich anschließend über Körperarterien und Arteriolen.":"Die linke Herzkammer drückt das Blut in eine große Körperarterie. Von dort wird es im Körper verteilt."}</p><div className="simple-cloze mt-5"><b>Arterie = vom Herzen weg</b></div></div><div className="panel"><h3 className="cardtitle">Welche Bereiche werden versorgt?</h3><p className="mt-2 text-slate-600">Klicke alle richtigen Körperbereiche an.</p><div className="body-targets mt-4">{targets.map(t=><button key={t} className={organs.includes(t)?"visited":""} onClick={()=>toggle(t)}>{organs.includes(t)?<Check/>:<Droplets/>}{t}</button>)}</div>{organs.length===4&&<Feedback ok text="Richtig: Die Gefäße verzweigen sich und erreichen den ganzen Körper."/>}</div></div>{hard&&<Task title="Erklärauftrag">Warum muss sich die Aorta in viele kleinere Arterien und Arteriolen verzweigen? Formuliere zwei zusammenhängende Sätze.</Task>}</Shell>}

const exchangeItems=[{q:"Sauerstoff",a:"zum Körper"},{q:"Nährstoffe",a:"zum Körper"},{q:"Kohlenstoffdioxid",a:"ins Blut"},{q:"Abfallstoffe",a:"ins Blut"}];
function ExchangeScreen({hard,answers,setAnswers}:{hard:boolean,answers:Record<number,string>,setAnswers:(v:Record<number,string>)=>void}){const done=exchangeItems.every((x,i)=>answers[i]===x.a);return <Shell n={4} title="Kapillaren: Hier findet der Austausch statt" time={hard?"8 Minuten":"7 Minuten"}><div className="panel"><div className="capillary-scene"><div className="capillary-tube">Blut in der Kapillare</div><div className="exchange-arrows">⇅</div><div className="body-cell">Körperzellen</div></div><p className="mt-5 leading-relaxed">{hard?"Kapillaren besitzen sehr dünne Wände und bilden dichte Netze. Dadurch sind die Wege kurz und Stoffe können zwischen Blut und Gewebe ausgetauscht werden.":"Kapillaren sind die feinsten Blutgefäße. Hier gibt das Blut Stoffe ab und nimmt andere Stoffe auf."}</p></div><div className="panel mt-5"><h3 className="cardtitle">Wohin bewegt sich der Stoff?</h3>{exchangeItems.map((x,i)=><div className="quizrow" key={x.q}><p>{x.q}</p><div>{["zum Körper","ins Blut"].map(o=><button key={o} className={`smallchoice ${answers[i]===o?"selected":""}`} onClick={()=>setAnswers({...answers,[i]:o})}>{o}</button>)}</div>{answers[i]&&<span className={answers[i]===x.a?"inline-ok":"inline-no"}>{answers[i]===x.a?"✓":"✗"}</span>}</div>)}{done&&<Feedback ok text="Der Stoffaustausch ist richtig zugeordnet. Nach der Sauerstoffabgabe wird das Blut sauerstoffarm dargestellt."/>}</div>{hard&&<Task title="Fachfrage">Erkläre, warum Kapillaren zahlreich, sehr fein und dünnwandig sein müssen.</Task>}</Shell>}

const easyVessels=[{q:"führt vom Herzen weg",a:"Arterie"},{q:"führt zum Herzen hin",a:"Vene"},{q:"gehört zum roten Hinweg",a:"Arterie"},{q:"gehört zum blauen Rückweg",a:"Vene"}];
const hardVessels=[...easyVessels,{q:"transportiert im Körperkreislauf unter höherem Druck",a:"Arterie"},{q:"wird durch Muskelpumpe und Klappen unterstützt",a:"Vene"}];
function ReturnScreen({hard,answers,setAnswers}:{hard:boolean,answers:Record<number,string>,setAnswers:(v:Record<number,string>)=>void}){const qs=hard?hardVessels:easyVessels;return <Shell n={5} title="Der blaue Rückweg: zurück zum Herzen" time={hard?"8 Minuten":"7 Minuten"}><div className="grid gap-4 md:grid-cols-2"><div className="vessel-card artery"><div className="vessel-tube"/><h3>Arterie</h3><p><b>A wie Ausgang:</b> vom Herzen weg.</p></div><div className="vessel-card vein"><div className="vessel-tube"><i/><i/></div><h3>Vene</h3><p>Zum Herzen hin; häufig mit Klappen.</p></div></div><div className="myth mt-5"><Brain/><div><strong>Wichtig: Die Richtung gibt den Namen.</strong><p>Im Körperkreislauf zeichnen wir Arterien rot und Venen blau. Entscheidend für den Namen ist aber nicht die Farbe, sondern die Fließrichtung.</p></div></div><div className="panel mt-5">{qs.map((x,i)=><div className="quizrow" key={x.q}><p>{x.q}</p><div>{["Arterie","Vene"].map(o=><button key={o} className={`smallchoice ${answers[i]===o?"selected":""}`} onClick={()=>setAnswers({...answers,[i]:o})}>{o}</button>)}</div>{answers[i]&&<span className={answers[i]===x.a?"inline-ok":"inline-no"}>{answers[i]===x.a?"✓":"✗"}</span>}</div>)}</div><div className="simple-cloze mt-5"><b>Ziel des Rückwegs:</b> Das sauerstoffarme Blut gelangt über die Hohlvenen in den rechten Vorhof.</div></Shell>}

function RouteScreen({hard,route,sequence,setSequence,result,check,reset}:{hard:boolean,route:string[],sequence:string[],setSequence:(v:string[])=>void,result:string,check:()=>void,reset:()=>void}){const options=hard?["Kapillaren","Hohlvenen","Aorta","rechter Vorhof","Venolen","Arteriolen","linke Herzkammer","Körpervenen","Körperarterien"]:["Körpervene","Körper","rechter Vorhof","linke Herzkammer","Körperarterie"];return <Shell n={6} title="Baue den vollständigen Blutweg" time={hard?"9 Minuten":"8 Minuten"}><div className="panel"><p className="text-lg font-black">Tippe die Begriffe in der richtigen Reihenfolge an.</p>{!hard&&<div className="hint mt-3"><CircleHelp/><span>Beginne bei der linken Herzkammer. Suche danach zuerst den Hinweg.</span></div>}<div className="mt-5 flex flex-wrap gap-3">{options.map(o=><button key={o} className="chip" disabled={sequence.includes(o)} onClick={()=>sequence.length<route.length&&setSequence([...sequence,o])}>{o}</button>)}</div><div className="flowline mt-6">{sequence.length?sequence.map((x,i)=><span className="flex items-center gap-2" key={x}><b>{x}</b>{i<sequence.length-1&&<ArrowRight size={17}/>}</span>):<span className="text-slate-400">Dein Blutweg erscheint hier …</span>}</div><div className="mt-5 flex gap-3"><button className="primary" disabled={sequence.length!==route.length} onClick={check}>Prüfen</button><button className="secondary" onClick={reset}><RotateCcw size={17}/> Neu</button></div>{result==="ok"&&<Feedback ok text="Der Körperkreislauf ist vollständig und richtig aufgebaut."/>}{result==="wrong"&&<Feedback text={hard?"Noch nicht. Beginne mit der linken Herzkammer und gehe vom größten arteriellen Gefäß zu immer feineren Gefäßen.":"Noch nicht. Tipp: linke Herzkammer → Körperarterie → Körper → Körpervene → rechter Vorhof"}/>}</div>{hard&&<Task title="Zusatz">Erkläre an deinem aufgebauten Weg, an welcher Stelle sich Sauerstoffgehalt und Modellfarbe verändern.</Task>}</Shell>}

function DrawingScreen({hard,checks,setChecks}:{hard:boolean,checks:Record<number,boolean>,setChecks:(v:Record<number,boolean>)=>void}){const items=hard?["Körperumriss und Herz eingezeichnet","linke Herzkammer und rechter Vorhof beschriftet","Aorta, Körperarterien und Arteriolen rot eingezeichnet","Kapillarnetze in Kopf, Armen, Organen und Beinen markiert","Venolen, Körpervenen und Hohlvenen blau eingezeichnet","Pfeile an allen Gefäßen gesetzt","Stoffaustausch an den Kapillaren notiert"]:["Körperumriss und Herz gezeichnet","linke Herzkammer beschriftet","roten Hinweg zum Körper gezeichnet","blauen Rückweg zum Herzen gezeichnet","rechter Vorhof beschriftet","Pfeile für die Richtung gesetzt"];const done=items.every((_,i)=>checks[i]);return <Shell n={7} title="Zeichenwerkstatt: Dein eigener Körperkreislauf" time={hard?"10 Minuten":"8 Minuten"}><div className="grid gap-5 md:grid-cols-[.8fr_1.2fr]"><div className="panel"><h3 className="cardtitle">Dein Auftrag</h3><p className="mt-3 leading-relaxed">Zeichne auf deinem Blatt einen Körperumriss mit Herz. Trage den vollständigen Körperkreislauf ein. Arbeite mit Rot, Blau und gut sichtbaren Pfeilen.</p><div className="color-key mt-5"><span><i className="key-red"/>Hinweg</span><span><i className="key-blue"/>Rückweg</span></div></div><div className="panel"><h3 className="cardtitle">Zeichnung kontrollieren</h3><div className="checklist mt-4">{items.map((x,i)=><label key={x}><input type="checkbox" checked={!!checks[i]} onChange={e=>setChecks({...checks,[i]:e.target.checked})}/><span>{x}</span></label>)}</div>{done&&<Feedback ok text="Deine Zeichnung enthält alle wichtigen Bestandteile."/>}</div></div>{hard&&<Task title="Partnerprüfung">Tauscht eure Zeichnungen. Eine Person verfolgt nur die Pfeile und spricht den Blutweg laut. Verbessert unklare Stellen.</Task>}</Shell>}

const finalQs=[{q:"Wo beginnt der Körperkreislauf?",a:"linke Herzkammer",o:["linke Herzkammer","rechter Vorhof","Körpervene"]},{q:"Wo findet der Stoffaustausch statt?",a:"Kapillaren",o:["Aorta","Kapillaren","Hohlvenen"]},{q:"Wohin führen Körpervenen?",a:"zum Herzen",o:["vom Herzen weg","zum Herzen","nur in die Beine"]},{q:"Wo endet der Körperkreislauf?",a:"rechter Vorhof",o:["linke Herzkammer","Aorta","rechter Vorhof"]}];
function FinalScreen({hard,answers,setAnswers,text,setText}:{hard:boolean,answers:Record<number,string>,setAnswers:(v:Record<number,string>)=>void,text:string,setText:(v:string)=>void}){
  const all=finalQs.every((x,i)=>answers[i]===x.a);
  const words=hard?["linke Herzkammer","Aorta","Arterien","Kapillaren","Venen","Hohlvenen","rechter Vorhof"]:[];
  const hits=words.filter(w=>text.toLowerCase().includes(w.toLowerCase())).length;
  return <Shell n={8} title="Kannst du den Körperkreislauf erklären?" time={hard?"8 Minuten":"6 Minuten"}><div className="panel"><h3 className="cardtitle">Abschluss-Check</h3>{finalQs.map((x,i)=><div className="quizrow" key={x.q}><p>{x.q}</p><div>{x.o.map(o=><button key={o} className={`smallchoice ${answers[i]===o?"selected":""}`} onClick={()=>setAnswers({...answers,[i]:o})}>{o}</button>)}</div>{answers[i]&&<span className={answers[i]===x.a?"inline-ok":"inline-no"}>{answers[i]===x.a?"✓":"✗"}</span>}</div>)}{all&&<Feedback ok text="Alle Grundfragen zum Körperkreislauf sind richtig beantwortet."/>}</div><div className="panel mt-5"><label className="block font-black">{hard?"Erkläre den Körperkreislauf in mindestens fünf zusammenhängenden Sätzen.":"Ergänze in 2–3 Sätzen: Der Körperkreislauf beginnt …"}<textarea className="answerbox" value={text} onChange={e=>setText(e.target.value)} placeholder={hard?"Der Körperkreislauf beginnt in der linken Herzkammer …":"Der Körperkreislauf beginnt in …"}/></label>{hard&&<div className="wordbank">Fachbegriffe verwendet: {hits}/7 · {words.join(" · ")}</div>}{all&&text.trim().split(/\s+/).length>8&&<div className="completion mt-5"><Check/><div><strong>Körperkreislauf geschafft!</strong><p>Du kannst Hinweg, Stoffaustausch und Rückweg nachvollziehen.</p></div></div>}</div></Shell>
}

function Choice({active,onClick,label}:{active:boolean,onClick:()=>void,label:string}){return <button onClick={onClick} className={`choice ${active?"active":""}`}>{active?<Check size={20}/>:<span className="h-5 w-5 rounded-full border-2 border-slate-300"/>}{label}</button>}
function Feedback({ok=false,text}:{ok?:boolean,text:string}){return <div role="status" className={`feedback ${ok?"ok":"no"}`}>{ok?<Check/>:<X/>}<span>{text}</span></div>}
function Task({title,children}:{title:string,children:React.ReactNode}){return <div className="task"><Brain/><div><strong>{title}</strong><p>{children}</p></div></div>}
